### ISSUE TITLE
什么时候优化下呗   自定义样式也不完善

### ISSUE THREAD

**Issue by mengzhidaren** [li-xiaojun/XPopupExt#4]
java.lang.IndexOutOfBoundsException: Index: 13, Size: 13
        at java.util.ArrayList.get(ArrayList.java:437)
        at com.lxj.xpopupext.popup.CityPickerPopup$3.onOptionsSelect(CityPickerPopup.java:82)
        at com.lxj.xpopupext.view.WheelOptions$3.onItemSelected(WheelOptions.java:155)
        at com.contrarywind.view.WheelView$1.run(WheelView.java:357)

**Comment by junixapp** [comment]
0.0.4已修复这个问题
